{% set name = "three.js" %}
{% set version = "107" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mrdoob/three.js/archive/r{{ version }}.tar.gz
  sha256: c09f63464d4121fceca07a77a022ade68a90961fb71b8930a99ad21500909f8f

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz
    mkdir -p $PREFIX/share
    mv $PREFIX/lib/node_modules/three $PREFIX/share/threejs
    ln -s $PREFIX/share/threejs $PREFIX/lib/node_modules/three

requirements:
  build:
    - nodejs

test:
  commands:
    - test -f $PREFIX/share/threejs/build/three.min.js  # [unix]

about:
  home: https://threejs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'JavaScript 3D library.'
  dev_url: https://github.com/mrdoob/three.js

extra:
  recipe-maintainers:
    - isuruf
