travis:
  secure:
    BINSTAR_TOKEN: PSKn3wdsUgtk8GTLxSr+8Ar4hGHbm4IN5iwWQ825aEU3pXmR0nmgEuo/0kTd9oq4vY3yWRkrF5wlvqtiORuWdnCyz8RQQ95DlX13LB03ijBXoUe64L2/YSPGCsq+9SUMjCukvjZ0ulYzbmwOIHQ9WtPTAUkFlXCi+BfuRTavHXeEV8Q7rCM85CY6Xvz6XS3QgNcQlMQ9TvPr4ADx7Z2RzXmW1sFgX9xt0GCNLo5ihV5d4vyPPao++YuNwX8gu1zKUmtXF8Nq1nFvxP9CDR0G8/BD7QLyujrblFSuaktdvnq/sSw5L8cTBZaOOLmSkNd0QfnbAWnDuvXPpjJ5leKzVJJwcCx1cQp2ry7kD53lqiKuOilx+7xUqdPs96XLwShUYFEflt+RBnU32O1VT/sxxB2WeHMLIx1hDAWLzro85Wh68JIZq/HP9ojQydUwkseklwxeDSxP/XxAPIYhi6FbcSNtfgKZU62qZBJJMBLV4A+BpcpVYwzsKkd50kLu7JlchI8IzBDyxER4qNcvfalTpBez/WqP/g+vp9/TR1I5LAYBhqoiGfYmC9p7012MPa92DlaQvOrDaWYyaSDHrg4D721VpQD1eWVHLl92viImxKUgrvtwz058mW6wmr+c8PhS12Ma7NaH3mtRaoFhsoPfqYUexk3wTPrHVmk2HVFOls0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
